FROM python:latest

RUN apt-get update && apt-get install -y \
  build-essential \
  python-dev-is-python3

WORKDIR /code

COPY requirements.txt .
RUN pip install --user -r requirements.txt

COPY mqtt-listener.py .
CMD ["python", "-u", "/code/mqtt-listener.py"]
